import nmi from "../images/nmi.png";
import tlp from "../images/tlp.png";
import rea from "../images/rea.png";
import rear from "../images/rear.png";
import bwom from "../images/bwom.png";
import ipt from "../images/ipt.png";
import wkh from "../images/wkh.png";
import memo from "../images/memo.png";
import ogs from "../images/ogs.png";
import aaa from "../images/aaa.png";
import marcus from "../images/marcus.png";
import coop from "../images/coop.png";
import gt from "../images/gt.png";
import etrump from "../images/etrump.png";
import gain from "../images/gain.png";
import fish from "../images/fish.png";
import tiny from "../images/tiny.png";
import chips from "../images/chips.png";
import vest from "../images/vest.png";
import pepe from "../images/pepe.png";
import goeth from "../images/goeth.png";
import niko from "../images/niko.png";
import exa from "../images/exa.png";
import meta from "../images/meta.png";
import compx from "../images/compx.png";
import coo from "../images/coo.png";
import fbet from "../images/fbet.png";
import kosh from "../images/kosh.png";
import fam from "../images/fam.png";

// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    name: "AAA",
    assetID: "2004387843",
    logo: aaa,
    vestigeLink: "https://vestige.fi/asset/2004387843",
    xLink: "https://x.com/algoadoptaaa",
    stableTVL: true,
    useCaseToken: false,
    memeToken: false,
    wrappedAsset: false,
  },
  // {
  //   name: "TDLD",
  //   assetID: "2176744157",
  //   logo: tdld,
  //   vestigeLink: "https://vestige.fi/asset/2176744157",
  //   xLink: "https://x.com/TinyDickLion",
  //   stableTVL: true,
  //   useCaseToken: false,
  //   memeToken: false
  //   wrappedAsset: false,
  // },
  {
    name: "NMI",
    assetID: "2279886826",
    logo: nmi,
    vestigeLink: "https://vestige.fi/asset/2279886826",
    xLink: "https://x.com/ConnectionMach",
    stableTVL: true,
    useCaseToken: false,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "BWOM",
    assetID: "2327984798",
    logo: bwom,
    vestigeLink: "https://vestige.fi/asset/2327984798",
    xLink: "https://x.com/bwombus",
    stableTVL: true,
    useCaseToken: false,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "IPT",
    assetID: "2342621554",
    logo: ipt,
    vestigeLink: "https://vestige.fi/asset/2342621554",
    xLink: "https://x.com/1nfinite0ne",
    stableTVL: true,
    useCaseToken: false,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "WKH",
    assetID: "2573477873",
    logo: wkh,
    vestigeLink: "https://vestige.fi/asset/2573477873",
    xLink: "https://x.com/HODL_TLP",
    stableTVL: true,
    useCaseToken: false,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "MEMO",
    assetID: "885835936",
    logo: memo,
    vestigeLink: "https://vestige.fi/asset/885835936",
    xLink: "https://x.com/AlgoMembers",
    stableTVL: true,
    useCaseToken: false,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "SQUAD",
    assetID: "1421321088",
    logo: ogs,
    vestigeLink: "https://vestige.fi/asset/1421321088",
    xLink: "https://x.com/OG_Squad_ALGO",
    stableTVL: true,
    useCaseToken: false,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "TLP",
    assetID: "987374809",
    logo: tlp,
    vestigeLink: "https://vestige.fi/asset/987374809",
    xLink: "https://x.com/TLPCoin",
    stableTVL: true,
    useCaseToken: false,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "REAR",
    assetID: "2413037774",
    logo: rear,
    vestigeLink: "https://vestige.fi/asset/2413037774",
    xLink: "https://x.com/TLPCoin",
    stableTVL: true,
    useCaseToken: false,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "REA",
    assetID: "1753483231",
    logo: rea,
    vestigeLink: "https://vestige.fi/asset/1753483231",
    xLink: "https://x.com/TLPCoin",
    stableTVL: true,
    useCaseToken: false,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "MARCUS",
    assetID: "2466866698",
    logo: marcus,
    vestigeLink: "https://vestige.fi/asset/2466866698",
    xLink: "https://x.com/MarcusFurrelius",
    stableTVL: true,
    useCaseToken: false,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "COOP",
    assetID: "796425061",
    logo: coop,
    vestigeLink: "https://vestige.fi/asset/796425061",
    xLink: "https://x.com/Coop_Daniels",
    stableTVL: true,
    useCaseToken: false,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "$GT",
    assetID: "2606098683",
    logo: gt,
    vestigeLink: "https://vestige.fi/asset/2606098683",
    xLink: "https://x.com/GreatToken1",
    stableTVL: true,
    useCaseToken: false,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "ETrump",
    assetID: "2705531863",
    logo: etrump,
    vestigeLink: "https://vestige.fi/asset/2705531863",
    xLink: "https://twitter.com/ETrumpParody",
    stableTVL: false,
    useCaseToken: false,
    memeToken: true,
    wrappedAsset: false,
  },
  {
    name: "GAIN",
    assetID: "1748330503",
    logo: gain,
    vestigeLink: "https://vestige.fi/asset/1748330503",
    xLink: "https://x.com/gaintoken",
    stableTVL: false,
    useCaseToken: true,
    wrappedAsset: false,
  },
  {
    name: "Fish",
    assetID: "2667006169",
    logo: fish,
    vestigeLink: "https://vestige.fi/asset/2667006169",
    xLink: "https://x.com/Fishsticks_algo",
    stableTVL: false,
    useCaseToken: false,
    memeToken: true,
    wrappedAsset: false,
  },
  {
    name: "TINY",
    assetID: "2200000000",
    logo: tiny,
    vestigeLink: "https://vestige.fi/asset/2200000000",
    xLink: "https://x.com/tinymanorg",
    stableTVL: false,
    useCaseToken: true,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "chip",
    assetID: "388592191",
    logo: chips,
    vestigeLink: "https://vestige.fi/asset/388592191",
    xLink: "https://x.com/algorandcasino",
    stableTVL: false,
    useCaseToken: true,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "VEST",
    assetID: "700965019",
    logo: vest,
    vestigeLink: "https://vestige.fi/asset/700965019",
    xLink: "https://x.com/vestigefi",
    stableTVL: false,
    useCaseToken: true,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "PEPE",
    assetID: "1096015467",
    logo: pepe,
    vestigeLink: "https://vestige.fi/asset/1096015467",
    xLink: "https://x.com/pepecoineth",
    stableTVL: false,
    useCaseToken: false,
    memeToken: false,
    wrappedAsset: true,
  },
  {
    name: "goETH",
    assetID: "386195940",
    logo: goeth,
    vestigeLink: "https://vestige.fi/asset/386195940",
    xLink: "https://x.com/ethereum",
    stableTVL: false,
    useCaseToken: false,
    memeToken: false,
    wrappedAsset: true,
  },
  {
    name: "NIKO",
    assetID: "1265975021",
    logo: niko,
    vestigeLink: "https://vestige.fi/asset/1265975021",
    xLink: "https://x.com/rxelms",
    stableTVL: false,
    useCaseToken: true,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "EXA",
    assetID: "1888888888",
    logo: exa,
    vestigeLink: "https://vestige.fi/asset/1888888888",
    xLink: "https://x.com/EXA_Market",
    stableTVL: false,
    useCaseToken: true,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "COMPX",
    assetID: "1732165149",
    logo: compx,
    vestigeLink: "https://vestige.fi/asset/1732165149",
    xLink: "https://x.com/compxlabs",
    stableTVL: false,
    useCaseToken: true,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "META",
    assetID: "712012773",
    logo: meta,
    vestigeLink: "https://vestige.fi/asset/712012773",
    xLink: "https://x.com/CometaHub",
    stableTVL: false,
    useCaseToken: true,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "COO",
    assetID: "891226062",
    logo: coo,
    vestigeLink: "https://vestige.fi/asset/891226062",
    xLink: "https://x.com/ghettopigeons",
    stableTVL: false,
    useCaseToken: true,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "FBET",
    assetID: "2456033705",
    logo: fbet,
    vestigeLink: "https://vestige.fi/asset/2456033705",
    xLink: "https://x.com/FanBetToken",
    stableTVL: false,
    useCaseToken: true,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "KOSH",
    assetID: "2583022095",
    logo: kosh,
    vestigeLink: "https://vestige.fi/asset/2583022095",
    xLink: "https://x.com/kingofshekels",
    stableTVL: false,
    useCaseToken: true,
    memeToken: false,
    wrappedAsset: false,
  },
  {
    name: "FAM",
    assetID: "2935126632",
    logo: fam,
    vestigeLink: "https://vestige.fi/asset/2935126632",
    xLink: "https://x.com/filippodotalgo",
    stableTVL: false,
    useCaseToken: true,
    memeToken: false,
    wrappedAsset: false,
  },
];

export const siteKey = "6LciRUEsAAAAAG9GTGdLXM2tNb-1GpMwHjv_LnJN";
